import React,{useEffect,useState} from 'react';
import {getApiUrl} from '../modules/config.js';
export default function RecoveryStatus(){
 const [data,setData]=useState(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function retry(issue){setBusy(true);try{const r=await fetch(getApiUrl()+'/api/admin/web3/credit-policy/retry',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({versionId:issue.version_id,username:issue.username})});const d=await r.json();setMessage(d.message);if(r.ok)setData(current=>({...current,issues:current.issues.map(x=>x===issue?{...x,retry_requested:true}:x)}));}catch{setMessage('No se pudo solicitar la revisión.');}finally{setBusy(false);}}
 useEffect(()=>{let active=true;async function load(){try{const r=await fetch(getApiUrl()+'/api/admin/web3/recovery-status',{credentials:'include',cache:'no-store'});const d=await r.json();if(active&&r.ok&&d.success)setData(d);}catch{}}load();const timer=setInterval(load,15000);return()=>{active=false;clearInterval(timer);};},[]);
 const states={pending:'En proceso',confirmed:'Confirmada',complete:'Aplicación completada',complete_with_issues:'Aplicada con cuentas pendientes de revisión',failed:'Rechazada por el contrato',superseded:'Sustituida por una política nueva',conflict:'Requiere revisión'};
 return <div><h3>Seguimiento de cambios</h3>{message&&<p role="status">{message}</p>}{!data?<p>No se pudo comprobar el seguimiento todavía.</p>:<><p>{data.operations.length} operaciones esperando confirmación o revisión.</p>{data.jobs.map(job=><p key={job.version_id}>Política {job.version_id}: {states[job.state]||job.state}. Cuentas revisadas hasta el identificador {job.cursor_id}; las excepciones se muestran por separado.</p>)}{(data.issues||[]).map(issue=><div key={issue.version_id+':'+issue.user_id}><p>@{issue.username||'Cuenta no disponible'} · Política {issue.version_id}: requiere revisión.</p><button disabled={busy||issue.retry_requested||issue.status==='retrying'||String(issue.version_id)!==String(data.jobs[0]?.version_id)||!issue.username} onClick={()=>retry(issue)}>{issue.retry_requested||issue.status==='retrying'?'Revisión en curso':'Reintentar con la política vigente'}</button></div>)}{data.operations.map(op=><details key={op.id}><summary>{states[op.state]||op.state}: {op.kind}</summary><p>Referencia {op.id}. {op.error_code||'La recuperación vuelve a comprobar esta transacción; no crea otra.'}</p></details>)}</>}</div>;
}
