'use strict';
const crypto=require('crypto');
const {Wallet}=require('ethers');
const service=require('../src/services/walletService');
const original=process.env.ENCRYPTION_SECRET;
beforeEach(()=>{process.env.ENCRYPTION_SECRET=crypto.randomBytes(32).toString('hex');});
afterAll(()=>{if(original===undefined)delete process.env.ENCRYPTION_SECRET;else process.env.ENCRYPTION_SECRET=original;});
test('missing encryption configuration fails closed',()=>{delete process.env.ENCRYPTION_SECRET;expect(()=>service.generateEncryptedWallet()).toThrow('no está configurada');});
test('generated wallet key matches its address',()=>{const account=service.generateEncryptedWallet();expect(new Wallet(service.decrypt(account.encryptedPrivateKey)).address).toBe(account.address);});
test('authenticated envelope rejects altered ciphertext',()=>{const value=service.encrypt('synthetic-private-material');const box=JSON.parse(Buffer.from(value.slice(3),'base64').toString());box.ciphertext=(box.ciphertext[0]==='0'?'1':'0')+box.ciphertext.slice(1);expect(()=>service.decrypt('v2:'+Buffer.from(JSON.stringify(box)).toString('base64'))).toThrow();});
test('legacy CBC is readable with the explicitly configured key',()=>{const iv=crypto.randomBytes(16),key=crypto.scryptSync(process.env.ENCRYPTION_SECRET,'salt',32),cipher=crypto.createCipheriv('aes-256-cbc',key,iv);const ciphertext=Buffer.concat([cipher.update('synthetic'),'utf8'&&cipher.final()]);expect(service.decrypt(iv.toString('hex')+':'+ciphertext.toString('hex'))).toBe('synthetic');});
test('an associated address without key is not replaced',async()=>{const client={query:jest.fn().mockResolvedValue({rows:[{id:1,web3_wallet_address:Wallet.createRandom().address}]})};await expect(service.setupTransactionPin(client,1,'729418')).rejects.toThrow('recuperación');expect(client.query).toHaveBeenCalledTimes(1);});
test('legacy key/address mismatch is rejected before any write',async()=>{const key=Wallet.createRandom();const client={query:jest.fn().mockResolvedValue({rows:[{id:1,web3_wallet_address:Wallet.createRandom().address,web3_private_key_encrypted:service.encrypt(key.privateKey)}]})};await expect(service.setupTransactionPin(client,1,'729418')).rejects.toThrow('no corresponde');expect(client.query).toHaveBeenCalledTimes(1);});
test('unsafe keystore parameters are rejected',async()=>{await expect(service.unlock({version:2,iterations:1000000000},'729418')).rejects.toThrow('no compatible');});
test('PIN must be a six-digit string',async()=>{await expect(service.setupTransactionPin({},1,'short')).rejects.toThrow('seis dígitos');});
