'use strict';
const router=require('express').Router();
const {rateLimit}=require('express-rate-limit');
const {authenticateToken}=require('../middleware/authMiddleware');
const {trustedOrigin}=require('../middleware/adminSession');
const {resolveWebAuthnRpContext}=require('../services/webauthnService');
const {RecoverableAccounts}=require('../services/recoverableAccounts');
let instance;
const service=()=>instance ||= new RecoverableAccounts(require('../config/db'));
router.use(authenticateToken,(req,res,next)=>{
    res.set('Cache-Control','no-store');
    if(req.method!=='GET'&&!trustedOrigin(req))return res.status(403).json({message:'Origen no autorizado.'});
    if(req.body&&['phrase','seed','mnemonic','pin','privateKey','passphrase'].some(k=>Object.hasOwn(req.body,k)))return res.status(400).json({message:'No envíes frases ni claves al servidor.'});
    next();
});
router.use(rateLimit({windowMs:15*60*1000,limit:120,keyGenerator:req=>String(req.user.userId),standardHeaders:true,legacyHeaders:false}));
const run=fn=>async(req,res)=>{try{res.json(await fn(req));}catch(e){res.status(e.status||503).json({success:false,message:e.status?e.message:'No se pudo verificar la cuenta. No se ha reemplazado su dirección.'});}};
router.get('/activation-readiness',run(req=>service().activationReadiness(req.user.userId)));
router.get('/status',run(req=>service().status(req.user.userId)));
router.post('/registration/options',run(req=>service().options(req.user.userId,resolveWebAuthnRpContext(req))));
router.post('/registration/verify',run(req=>service().register(req.user.userId,req.body)));
router.get('/activation/:id',run(req=>service().activationStatus(req.user.userId,req.params.id)));
router.post('/activation/:id',run(req=>service().activate(req.user.userId,req.params.id,req.body)));
const recovery=()=>new (require('../services/personalRecovery').PersonalRecovery)(service());
router.get('/recovery/status',run(req=>recovery().status(req.user.userId)));
router.post('/recovery/options',run(req=>recovery().options(req.user.userId,resolveWebAuthnRpContext(req))));
router.post('/recovery/prepare',run(req=>recovery().prepare(req.user.userId,req.body)));
router.post('/recovery/submit',run(req=>recovery().submit(req.user.userId,req.body)));
router.post('/recovery/:id/advance',run(req=>recovery().advance(req.user.userId,req.params.id)));
router.post('/recovery/:id/finalize',run(req=>recovery().finalize(req.user.userId,req.params.id)));
router.get('/recovery/:id/cancel',run(req=>recovery().cancelQuote(req.user.userId,req.params.id)));
router.post('/recovery/:id/cancel',run(req=>recovery().cancel(req.user.userId,req.params.id,req.body)));
module.exports=router;
