name: Deploy Frontend to Hostinger

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  web-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Obtener el codigo
        uses: actions/checkout@v4
        
      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Instalar dependencias y Construir (Build)
        run: |
          cd frontend
          npm install
          npm run build
      
      - name: Sincronizar archivos por lftp (Script Nativo)
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          sudo apt-get update && sudo apt-get install -y lftp
          cd frontend/dist
          lftp -c "set ssl:verify-certificate no; open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_SERVER; mirror -Rnev ./ ./ --parallel=10"
