name: Deploy Frontend to Hostinger

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  web-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Obtener el codigo
        uses: actions/checkout@v4
        
      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Instalar dependencias y Construir (Build)
        run: |
          cd frontend
          npm install
          npm run build
      
      - name: Sincronizar archivos por FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./frontend/dist/
          server-dir: /
